version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sqs,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infra/scripts/create-infra.sh:/etc/localstack/init/ready.d/create-infra.sh